SELECT A.CAR_ID, A.CAR_TYPE, TRUNCATE((A.DAILY_FEE * ((100 - B.DISCOUNT_RATE) / 100)) * 30, 0) AS FEE

FROM CAR_RENTAL_COMPANY_CAR AS A

JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B ON A.CAR_TYPE = B.CAR_TYPE

# WHERE (A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV') AND A.CAR_ID IN (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE ('2022-11-30' < START_DATE OR '2022-11-01' > END_DATE)
# ) AND B.DURATION_TYPE = '30일 이상'

WHERE 
(A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV') AND 
A.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-30' AND '2022-11-01' <= END_DATE) AND B.DURATION_TYPE = '30일 이상'

GROUP BY A.CAR_ID

HAVING 500000 <= FEE AND FEE < 2000000

ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC