SELECT A.CAR_ID, A.CAR_TYPE, 
       TRUNCATE((A.DAILY_FEE * 30) * ((100 - C.DISCOUNT_RATE) / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C 
    ON A.CAR_TYPE = C.CAR_TYPE 
   AND C.DURATION_TYPE = '30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B 
    ON A.CAR_ID = B.CAR_ID
   AND B.START_DATE <= '2022-11-30'
   AND B.END_DATE >= '2022-11-01'
WHERE (A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV')
  AND B.CAR_ID IS NULL -- 대여 기록이 없는 차량 필터링
HAVING FEE >= 500000 AND FEE <= 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;
