SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME

FROM ANIMAL_INS AS A

JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID

WHERE (A.SEX_UPON_INTAKE = 'Intact Male' or A.SEX_UPON_INTAKE = 'Intact Female') AND
(B.SEX_UPON_OUTCOME = 'Neutered Male' or B.SEX_UPON_OUTCOME = 'Spayed Female')

ORDER BY A.ANIMAL_ID














# SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
# FROM ANIMAL_INS AS I

# JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID

# WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND O.SEX_UPON_OUTCOME NOT LIKE 'Intact%'

# ORDER BY I.ANIMAL_ID ASC