SELECT 
    YEAR(B.SALES_DATE) AS YEAR, 
    MONTH(B.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT B.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT B.USER_ID) / 
    (SELECT COUNT(*)
        FROM USER_INFO
        WHERE JOINED LIKE '2021%')
    , 1) AS PURCHASED_RATIO
FROM USER_INFO AS A
JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
WHERE A.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;
















# SELECT YEAR(ONS.SALES_DATE) AS YEAR, 

# MONTH(ONS.SALES_DATE) AS MONTH, 

# COUNT(DISTINCT ONS.USER_ID) AS PURCHASED_USERS, 

# ROUND(COUNT(DISTINCT ONS.USER_ID) / COUNT(DISTINCT UI.USER_ID), 1) AS PURCHASED_RATIO

# FROM ONLINE_SALE AS ONS

# JOIN USER_INFO AS UI ON UI.USER_ID = ONS.USER_ID

# WHERE UI.JOINED LIKE '2021%'

# GROUP BY 
#     YEAR, MONTH

# ORDER BY YEAR ASC, MONTH ASC