-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK, AUTHOR, BOOK_SALES
WHERE AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID AND 
BOOK.BOOK_ID = BOOK_SALES.BOOK_ID AND 
BOOK_SALES.SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY DESC