SELECT FP.PRODUCT_ID,
FP.PRODUCT_NAME,
SUM(FO.AMOUNT) * FP.PRICE AS TOTAL_SALES

FROM FOOD_PRODUCT AS FP

LEFT JOIN FOOD_ORDER AS FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
AND FO.PRODUCE_DATE LIKE '2022-05%'

GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME

HAVING TOTAL_SALES IS NOT NULL

ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC