SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR

    UNION ALL  -- 중복 허용
     
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
) AS Combined
GROUP BY FLAVOR
ORDER BY SUM(TOTAL) DESC  -- GROUP BY 후 합산된 TOTAL을 기준으로 정렬
LIMIT 3;
