SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE

FROM REST_REVIEW AS A

JOIN MEMBER_PROFILE AS B ON A.MEMBER_ID = B.MEMBER_ID

WHERE A.MEMBER_ID = (SELECT A.MEMBER_ID
     FROM MEMBER_PROFILE AS A
     JOIN REST_REVIEW AS B ON A.MEMBER_ID = B.MEMBER_ID
     GROUP BY A.MEMBER_ID
     ORDER BY COUNT(A.MEMBER_ID) DESC
     LIMIT 1)

ORDER BY A.REVIEW_DATE ASC, A.REVIEW_TEXT ASC